### PR TITLE
Add Private endpoint capability

### PR DESCRIPTION
**Pull request by bioinformaticsbejo**
Adds Private Endpoint integration

sorry for the 100+ commits.

### CODE REVIEW

**Comment by shibayan** [comment]
This PR cannot be merged.

The reason is that there are very few scenarios in which Private Endpoints need to be used, and the majority of users do not need them, yet we need to force a disruptive change.

Please modify the forked module and use it.

**Comment by bioinformaticsbejo** [comment]
Hi @shibayan 

Thanks for the quick response,

I can't see a scenario where I would leave all my DNS open to the whole internet.

The way I coded, with the subnet in a list, if you don't set it up there will be no change in the deployment and it will work as before.

Regards

**Comment by shibayan** [comment]
The decision to use Private Endpoint should be left to the user. In your scenario, a Private Endpoint may be essential, but for many users it is not.

**Comment by bioinformaticsbejo** [comment]
@shibayan  agreed. that's why it is still optional in the code.
anyways. thanks for the awesome tool.
works like a charm
regards

**Pull request closed without merging**
